<template>
  <div class="q-pa-md">
    <q-card style="max-width: 210px">
      <q-skeleton height="160px" square />
      <q-item>
        <q-item-section>
          <q-item-label>
            <q-skeleton type="text" class="q-my-sm" />
          </q-item-label>
          <q-item-label caption>
            <q-skeleton type="text" class="q-my-sm" />
          </q-item-label>
          <q-item-label caption>
            <q-skeleton type="text" />
          </q-item-label>
        </q-item-section>
      </q-item>
    </q-card>
  </div>
</template>
